[project]
name = "hdbscan-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "hdbscan>=0.8.40",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
]
